################################################################################
# BUILD
################################################################################

[build]
  publish = ".next"

[context.deploy-preview]
  command = "npm run build:preview"

[context.production]
  command = "npm run build:production"

################################################################################
# PLUGINS
################################################################################

[[plugins]]
  package = "@netlify/plugin-nextjs"

################################################################################
# REDIRECTS
################################################################################

[[redirects]]
  from = "/japan-blog"
  to = "/japan"

[[redirects]]
  from = "/malaysia-blog"
  to = "/malaysia"

[[redirects]]
  from = "/philippines-blog"
  to = "/philippines"

[[redirects]]
  from = "/philippines-videos"
  to = "/philippines"

[[redirects]]
  from = "/vietnam-blog"
  to = "/vietnam"

[[redirects]]
  from = "/blog/categories/america"
  to = "/america"

[[redirects]]
  from = "/blog/categories/japan"
  to = "/japan"

[[redirects]]
  from = "/blog/categories/malaysia"
  to = "/malaysia"

[[redirects]]
  from = "/blog/categories/philippines"
  to = "/philippines"

[[redirects]]
  from = "/blog/categories/vietnam"
  to = "/vietnam"

[[redirects]]
  from = "/post/breathtaking-examples-of-architecture-around-the-world"
  to = "/post/worlds-busiest-intersection-shibuya-crossing"

[[redirects]]
  from = "/post/japan-for-beginners-5-things-you-must-do"
  to = "/post/3-things-to-do-in-hanoi-vietnams-old-quarter"

[[redirects]]
  from = "/post/the-everlasting-magic-of-mediterranean-seaside-villages"
  to = "/post/5-travel-destinations-tourists-miss"
